fgpv-vpgf/fgpa-apgf

- LICENSE
- README.md
- pull_request_template.md
Closes #1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/12)
> chore(doc): Add documentation file to repo

- src/app/ui/forms/form.html
- src/app/ui/header/header.html
- src/app/ui/summary/summary.html
- src/app/ui/tab/tab.html
- src/content/samples/fgpv-author.tpl
- src/content/styles/modules/_all.scss
- src/content/styles/modules/_forms.scss
- src/content/styles/modules/_header.scss
- src/content/styles/modules/_summary.scss
- src/content/styles/vendor/_all.scss
Closes #53
Improve look and feel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/54)
> layout(general): set forms to take available room

- src/app/app-seed.js
- src/app/core/modelManager.service.js
- src/app/layout/layout-loader.js
- src/app/layout/shell.directive.js
- src/app/layout/shell.html
- src/app/ui/forms/form.html
- src/app/ui/forms/form.service.js
- src/app/ui/forms/service/service.directive.js
- src/app/ui/tree/tree.html
- src/app/ui/ui-loader.js
- src/content/samples/config/config-author.en-CA.json
- src/content/samples/config/config-preview.json
- src/content/samples/fgpv-author.tpl
- src/content/styles/modules/_all.scss
- src/content/styles/modules/_effects.scss
- src/content/styles/modules/_forms.scss
- src/content/styles/modules/_loading.scss
- src/content/styles/vendor/_all.scss
- src/content/styles/vendor/_bootstrap.scss
- src/locales/translations.csv
- src/schemas/schemaForm/service.en-CA.json
- src/schemas/schemaForm/service.fr-CA.json
First draft of the service form
Chrome, FF, Safari
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/56)
> feat(form): Add service form

- package.json
- scripts/genSchemas.js
- scripts/genSchemasDependencies.svg
- src/locales/genSchemas.csv
- src/locales/genSchemasValues.csv
- src/schemas/schemaForm1/circular.en-CA.json
- src/schemas/schemaForm1/circular.fr-CA.json
- src/schemas/schemaForm1/header.en-CA.json
- src/schemas/schemaForm1/header.fr-CA.json
- src/schemas/schemaForm1/language.en-CA.json
- src/schemas/schemaForm1/language.fr-CA.json
- src/schemas/schemaForm1/map.en-CA.json
- src/schemas/schemaForm1/map.fr-CA.json
- src/schemas/schemaForm1/schema.json
- src/schemas/schemaForm1/schemaAuthor.json
- src/schemas/schemaForm1/schemaAuthorBefProp.json
- src/schemas/schemaForm1/services.en-CA.json
- src/schemas/schemaForm1/services.fr-CA.json
- src/schemas/schemaForm1/ui.en-CA.json
- src/schemas/schemaForm1/ui.fr-CA.json
- src/schemas/schemaForm1/version.en-CA.json
- src/schemas/schemaForm1/version.fr-CA.json
Add: source file, JSON files, csv files;
Put files at appropriate places in fgpa repo hierachy;
Modify source file to reflect new files localisations;
Modify source file after Linter analysis;
Update Package.json.
Closes #55
fgpv-vpgf/fgpa-apgf/issues/55
Yes, on console
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/57)
> add(feat): fgpa-schema-splitter integration part 1

- src/app/ui/forms/service/service.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/header/header.directive.js
- src/content/samples/config/config-author.en-CA.json
- src/locales/translations.csv
- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
Closes #39
Add UI form section
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/62)
> feat(form): Add ui form

- package.json
- scripts/genSchemas.csv
- scripts/genSchemas.js
- scripts/genSchemasDependencies.svg
- scripts/genSchemasValues.csv
- src/schemas/schemaForm1/circular.en-CA.json
- src/schemas/schemaForm1/circular.fr-CA.json
- src/schemas/schemaForm1/header.en-CA.json
- src/schemas/schemaForm1/header.fr-CA.json
- src/schemas/schemaForm1/language.en-CA.json
- src/schemas/schemaForm1/language.fr-CA.json
- src/schemas/schemaForm1/map.en-CA.json
- src/schemas/schemaForm1/map.fr-CA.json
- src/schemas/schemaForm1/schema.json
- src/schemas/schemaForm1/schemaAuthor.json
- src/schemas/schemaForm1/schemaAuthorBefProp.json
- src/schemas/schemaForm1/services.en-CA.json
- src/schemas/schemaForm1/services.fr-CA.json
- src/schemas/schemaForm1/ui.en-CA.json
- src/schemas/schemaForm1/ui.fr-CA.json
- src/schemas/schemaForm1/version.en-CA.json
- src/schemas/schemaForm1/version.fr-CA.json
Add schema in pieces, script and translation files at appropriate
places.
Update package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/69)
> add(feat): merge fpga-schema-splitter

- src/app/addon/addon-loader.js
- src/app/addon/sampleForm/sampleForm.module.js
- src/app/addon/sampleSchema/sampleSchema.module.js
- src/app/app-loader.js
- src/app/app.module.js
- src/app/core/constant.service.js
- src/app/layout/accordion.directive.js
- src/app/layout/layout-loader.js
- src/app/ui/forms/bindValues.directive.js
- src/app/ui/forms/form.html
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/ui-loader.js
- src/content/samples/config/config-author.en-CA.json
- src/content/samples/config/config-preview.json
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
- src/schemas/schemaForm/test.fr-CA.json
Closes #61
Add map form. At the same time I added functions to update form, form inside index and model inside the index from model value. I also added functionalities to do Angular Schema Form. I put sample to help in futur developement
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/75)
> feat(form): Add map form

- src/app/ui/forms/map/map.directive.js
- src/content/samples/config/config-author.en-CA.json
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
Closes #79
Add missing part for layers and legend.
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/85)
> feat(form): add missing part to map form

- src/app/layout/accordion.directive.js
- src/app/ui/forms/map/map.directive.js
Closes #84
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/87)
> feat(form): ability to have collapsible element collapsed by default

- src/app/app-seed.js
- src/app/core/constant.service.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/summary/summary.directive.js
- src/app/ui/ui-loader.js
- src/content/samples/config/config-author.en-CA.json
- src/content/samples/config/config-preview-sample.json
- src/content/samples/frame-preview.tpl
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/services.en-CA.json
- src/schemas/schemaForm/services.fr-CA.json
- src/schemas/schemaForm1/services.en-CA.json
Closes #82
Make the preview work with the actual configuration instead of a predefine one
Chrome, Firefox and Edge
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/93)
> feat(summary): make preview work with real data

- src/app/core/constant.service.js
- src/app/core/modelManager.service.js
- src/app/ui/forms/language/language.directive.js
- src/app/ui/forms/version/version.directive.js
- src/app/ui/header/header.directive.js
- src/app/ui/summary/summary.directive.js
- src/app/ui/ui-loader.js
- src/content/samples/config/config-author.en-CA.json
- src/content/styles/modules/_loading.scss
- src/locales/translations.csv
- src/schemas/schemaForm/language.en-CA.json
- src/schemas/schemaForm/language.fr-CA.json
- src/schemas/schemaForm/version.en-CA.json
- src/schemas/schemaForm/version.fr-CA.json
Closes #91, #92
Add the form section for language and version
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/95)
> feat(form): Add version and language form section

- src/app/core/common.service.js
- src/app/core/constant.service.js
- src/app/core/modelManager.service.js
- src/app/layout/accordion.directive.js
- src/app/layout/shell.directive.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/language/language.directive.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/forms/version/version.directive.js
- src/app/ui/header/header.directive.js
- src/content/samples/config/config-author.fr-CA.json
- src/content/styles/vendor/_bootstrap.scss
Closes #80
Fix some bugs when we load a configuration file. At the same time on new, load and language switch events:
- add the splash to hide form reset.
- reset the form to make sure it is always up to date
- reset if need be the showAdvance fields because when form is reset, we lost the link between the checkbox and the show/hide advance
- reset the accordion
Also, add constant where we use $timeout to make modification easier.
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> fix(load): fix config file load

- src/app/addon/dynamicSelect/dynamicSelect.module.js
- src/app/core/modelManager.service.js
- src/app/ui/forms/dynamicSelect.directive.js
- src/app/ui/forms/map/map.directive.js
Closes #90
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/97)
> fix(form): initialBasemapId doesn't work properly

- src/app/ui/summary/summary.directive.js
- src/content/samples/frame-preview.tpl
Closes #94
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/98)
> feat(preview): make it work with the selected language

- src/app/core/modelManager.service.js
- src/app/ui/forms/map/map.directive.js
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #83 , #88 
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/102)
> fix(config), feat(form): remove $$haskkey from config and add overviewUrl to have static overview map

- src/app/core/core.run.js
- src/content/samples/fgpv-author.tpl
- src/polyfill/ie.assign.js
- src/polyfill/polyfill-loader.js
Closes #107
Add polyfill and redo the way event for schemaupdate is broadcast to solve IE bugs.
IE, Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/110)
> fix(IE): Doesn't work in IE 11

- src/content/styles/modules/_forms.scss
- src/content/styles/vendor/_all.scss
- src/content/styles/vendor/_bootstrap.scss
- src/content/styles/vendor/_shame.scss
Closes #109
Modify somee css with specific hack for IE
Chrome, IE
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/112)
> style(IE): modify css to make it work in IE

- src/app/layout/accordion.directive.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/styles/modules/_forms.scss
- src/content/styles/vendor/_bootstrap.scss
- src/content/styles/vendor/_shame.scss
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #111
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/113)
> feat(form): Add expand and collapse all for basemaps and layers

- src/app/geo/geo-loader.js
- src/app/geo/projection.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/extent/extent-dialog.html
- src/app/ui/forms/map/map.directive.js
- src/content/samples/config/config-extent.json
- src/content/samples/extensions/extent.js
- src/content/samples/frame-extent.tpl
- src/content/styles/modules/_dialog.scss
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
- webpack.common.js
Closes #17
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/119)
> feat(form): Add set extent from map

- src/app/core/common.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/samples/config/config-full.json
- src/content/samples/fgpv-author.tpl
- src/content/styles/modules/_forms.scss
Closes #122
Add update of accordion header for nested array
Chrome, FF, Safari and IE
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/123)
> feat(form): Add nested array form (accordion) update

- src/app/core/constant.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/content/samples/frame-extent.tpl
Closes #132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/136)
> fix(form): update field name when added from add field button

- src/app/core/modelManager.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #133
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/137)
> feat(legend): Add text input to write legend in JSON

- src/app/ui/forms/form.service.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/header/header.directive.js
- src/app/ui/header/header.html
- src/content/styles/modules/_header.scss
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
Closes #128, #127, #126, #135
For #135, we can't have the real saved name if there is a duplicate. We will need to change from FileSaver to another library
Fix bugs and add feature submitted by user feedback
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/138)
> fix(form): Fix user feedback needs

- .eslintrc.yml
- src/app/core/modelManager.service.js
- src/app/ui/forms/map/map.directive.js
Before: basemaps, layers, tileSchemas, extentSets and lodSets are not
listed in the summary
After: add lists for basemaps, layers, tileSchemas, extentSets and
lodSets in the summary
Element validitidy state is not set for the moment.
Closes #116
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/143)
> add(feat): add list of map elements in summary

- src/app/core/modelManager.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #140
Remove the "remove" checkbox and set the default ASF array remove. To solve the problem, we set the array as not empty by default and hide the non useful field with css until valid fields are set
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/150)
> fix(form): Add remove button for field

- src/app/ui/header/header.directive.js
Closes #147
Chrome, FF, Safari, EI, Edge
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/158)
> fix(save): Fix save in IE and Edge

- src/app/core/common.service.js
- src/app/core/stateManager.service.js
- src/app/ui/forms/language/language.directive.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/forms/version/version.directive.js
Before:
-Missing validation on undefined items
-Missing validation icons for layers, basemaps, tileSchemas, extents and lods
After:
-Add global validation function to be used by PREVIEW
-Add validation of undefined elements
-Add validation icon for layers, basemaps, tileSchemas, extents and lods
Closes #139,#142,#151
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/165)
> add(core): consolidate validity

- .eslintrc.yml
- src/app/core/core-loader.js
- src/app/core/core.run.js
- src/app/core/external.service.js
- src/app/ui/header/header.directive.js
- src/app/ui/summary/summary.html
- src/content/samples/extensions/ddr/ddr-tools.js
- src/content/samples/extensions/ddr/ddr.css
- src/content/samples/extensions/ddr/ddr.js
- src/content/samples/extensions/ddr/frame-ddr.html
- src/content/samples/fgpv-author.tpl
- webpack.common.js
Closes #159
We can now send file to DDR from the authoring tool with this extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/169)
> feat(ddr): Link authoring tool to DDR

- src/app/core/common.service.js
- src/app/core/constant.service.js
- src/app/core/core.run.js
- src/app/core/stateManager.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/summary/summary.directive.js
- src/app/ui/tree/tree.directive.js
- src/app/ui/tree/tree.html
- src/locales/translations.csv
Add hyperlinks between summary and sub-tab
Add hyperlinks between layers and basemaps with their corresponding section in the form
Add hyperlinks between map legend section and ui legend section
Closes #134,#164,#182
Chrome and Firefox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/183)
> add(summary): sub-tab link

- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
Closes #178
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/185)
> fix(form): dynamic select choice doesn't copyValueTo for array

- src/app/ui/forms/map/map.directive.js
- src/content/samples/config/config-authorA.json
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
Closes #180
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/187)
> feat(legend): Add snippet of config to create 4 legend groups

- .eslintrc.yml
- src/app/core/constant.service.js
- src/app/core/stateManager.service.js
- src/app/ui/summary/summary.directive.js
- src/app/ui/tree/tree.html
- src/content/styles/modules/_summary.scss
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Before: some empty tileSchemas, extents, lods, layers and basemaps
mandatory parameters are not detected by validation process.
Also, missing title in summary when id or name parameters are empty
Missing overall validation for tileSchemas, extents, lods, layers and basemaps
After: add corresponding require in schemas map.[lang].json.
Add special title for the summary if one is missing.
Add global validation for tileSchemas, extents, lods, layers and basemaps
Closes #167,#179
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> add(core): add validation process for map and spatial items

- src/app/ui/tree/tree.html
Changed the icon so closed is a right arrow and open is a down arrow
- [x ] PR targets the correct release version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/192)
> fix(tree) : fix arrow used for open/closed

- src/app/core/common.service.js
- src/app/core/external.service.js
- src/app/core/stateManager.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/lods/lods-dialog.html
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/app/ui/header/header.directive.js
- src/app/ui/summary/summary.directive.js
- src/content/styles/modules/_dialog.scss
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
Closes #174
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/193)
> feat(form): Add automatique lods population from service

- src/content/samples/extensions/ddr/ddr-tools.js
- src/content/samples/extensions/ddr/ddr.js
- src/content/samples/extensions/ddr/frame-ddr.html
Closes #172
Fix problems with IE11. Those problems are cause by IE not able to deal properly with ES6 syntax. We close this issue for now but we will have to open a new issue to check with IE after we finish to add new functions to DDR
IE
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/194)
> fix(ddr): Not working in IE11 because of ES6

- src/content/samples/fgpv-author.tpl
Closes #198
Check google fgp analytic account and it shows up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/212)
> core(tracking) Add google analytic to main page

- package-lock.json
- src/app/core/core.run.js
- src/content/samples/extensions/ddr/ddr-tools.js
- src/content/samples/extensions/ddr/ddr.css
- src/content/samples/extensions/ddr/ddr.js
- src/content/samples/extensions/ddr/frame-ddr.html
Closes #196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/213)
> feat(ddr): Add ui section from mockups for neww functionnalities

- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/samples/frame-preview.tpl
- src/locales/help/info-basemaps-en-CA.md
- src/locales/help/info-basemaps-fr-CA.md
- src/locales/help/info-extentlods-en-CA.md
- src/locales/help/info-extentlods-fr-CA.md
- src/locales/help/info-layers-en-CA.md
- src/locales/help/info-layers-fr-CA.md
- src/locales/help/info-legend-en-CA.md
Closes #215
Add id automatically for layers, basemaps and tile schema from the name attribute.
Chrome
with existing and new value
Modified the related makdown
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/226)
> feat(form): Add id value automatically from name value

- src/app/core/constant.service.js
- src/app/core/stateManager.service.js
Problem come from the jquery selector and the modification of tabs order
Closes #222
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/223)
> fix(summary): setItemId problem for layers and basemaps

- src/app/core/core.run.js
- src/app/ui/header/error-dialog.html
- src/app/ui/header/header.directive.js
- src/app/ui/header/header.html
- src/content/styles/modules/_dialog.scss
- src/locales/translations.csv
Closes #218, #224
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/225)
> feat(header): make new file more obvious and show message when file upload fails

- src/app/ui/header/header.html
Closes #228
Chrome
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/229)
> fix(header): Not able to upload same file twice

- webpack.common.js
closes #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/231)
> fix(cleanbuild): remove index_author.html

- src/app/core/constant.service.js
- src/app/core/core.config.js
- src/app/layout/accordion.directive.js
- src/app/layout/detect-scrollbar.directive.js
- src/app/layout/layout-loader.js
- src/app/ui/header/header.directive.js
- src/app/ui/header/header.html
- src/app/ui/header/help-dialog.html
- src/app/ui/header/help-search.directive.js
- src/app/ui/header/help-search.html
- src/app/ui/header/help.service.js
- src/app/ui/ui-loader.js
- src/content/samples/frame-preview.tpl
- src/content/styles/common/_all.scss
- src/content/styles/layout/_accordion.scss
- src/content/styles/layout/_all.scss
- src/content/styles/modules/_all.scss
- src/content/styles/modules/_dialog.scss
- src/content/styles/modules/_help.scss
- src/content/styles/vendor/_all.scss
- src/content/styles/vendor/_angularmaterial.scss
- src/locales/help/en-CA.md
- src/locales/help/fr-CA.md
- src/locales/translations.csv
Closes #227
Add accordion to separate section content and a search box to highlight selection.
Chrome, Firefox, Safari
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/232)
> feat(help): Add accordion and search to help

- src/app/ui/forms/map/map.directive.js
Closes #230
Set the fields array automatically from the url and index. This will make the "show table" work inside preview even if user doesn't set the fields manually.
Chrome, FF and Safari
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/234)
> fix(map): Fields not define by default

- src/content/styles/modules/_dialog.scss
Closes #235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/240)
> fix(dialog): content doesn't expand to container

- src/content/samples/fgpv-author.tpl
Closes #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/245)
> fix(html): No locals for French page

- src/app/ui/forms/map/map.directive.js
closes #216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/233)
> fix(hide-ro-fields): hide read only fields

- src/app/geo/layer.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/samples/config/config-full.json
- src/content/samples/fgpv-author.tpl
Closes #246
Was only testing for SHAPE, make it case insensitive
We also had bad controls enum when updated fields array. Remove problems in layers.services.js
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/247)
> fix(map): Shape isn't removed and errors are introduced

- src/app/geo/layer.service.js
- src/app/ui/forms/map/map.directive.js
Closes #248
Chrome
Inline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/252)
> fix(map): Layers are link together when we add new one

- src/app/geo/gapi.service.js
- src/app/geo/geo-loader.js
- src/app/geo/layer.service.js
- src/app/geo/projection.service.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/237)
> fix(addjsdoc): add jsdoc for geo

- src/app/addon/addon-loader.js
- src/app/layout/detect-scrollbar.directive.js
closes #191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/253)
> fix(jsdocaddon) add missing jsdoc  addon

- src/content/samples/config/config-authorB.json
Closes #255
Update configB because about was missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/261)
> fix(ui): Set about in demo config file

- src/app/addon/addon-loader.js
closes #191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/263)
> jsdoc(addon) : add missing jsdoc

- src/app/geo/layer.service.js
- src/app/layout/dragHandle.directive.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/265)
> fix(performance): Optimize performace for huge config

- src/app/ui/forms/map/map.directive.js
Closes #269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/275)
> feat(legend): Reinit layer id selection

- src/app/layout/dragHandle.directive.js
- src/app/layout/layout-loader.js
- src/app/layout/shell.directive.js
closes #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/267)
> jsdoc(layout) add missing jsdoc

- src/app/core/common.service.js
- src/app/core/core-loader.js
- src/app/core/debounce.service.js
- src/app/core/external.service.js
- src/app/core/modelManager.service.js
- src/app/core/recursion.service.js
closes #205
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)
> jsdoc(core) add missing jsdoc

- src/app/core/constant.service.js
- src/app/core/core.run.js
- src/app/core/modelManager.service.js
- src/app/ui/header/header.directive.js
Closes #290, #292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/297)
> feat(load): Load config file from url options

- src/app/ui/forms/map/map.directive.js
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/317)
> fix(form): set minimum and maximum value for opacity

- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/locales/help/en-CA.md
- src/locales/help/fr-CA.md
- src/locales/translations.csv
- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
Closes #315
Add title map for all enum except enum who holds type like layer type, field type, ...
It doesn't work for side menu because it is enum inside an array. The code is there to revisit in the futur.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/318)
> fix(layout): Add title map for enum

- src/app/layout/accordion.directive.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/locales/translations.csv
Closes #284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/322)
> fix(filter): validate selector value to make sure it follows syntax

- src/app/ui/forms/map/map.directive.js
Closes #319
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/324)
> fix(map): remove 'remove' property from columns

- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
- [X ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [X ] PR targets the correct release version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/327)
> fix(help): fix help instruction basemapselctor

- src/app/ui/summary/summary.html
- src/locales/help/en-CA.md
- src/locales/help/fr-CA.md
- src/locales/help/info-extentlods-en-CA.md
- src/locales/help/info-extentlods-fr-CA.md
- src/locales/help/info-legend-en-CA.md
- src/locales/help/info-legend-fr-CA.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/329)
> fix(hyperlink): open links in new window

- src/app/ui/forms/services/services.directive.js
- src/app/ui/forms/ui/ui.directive.js
- src/content/styles/base/_all.scss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/335)
> feat(textarea): make aboutmap footnote textarea

- wiki/schema-map.en-CA.md
- wiki/schema.en-CA.md
-Update wiki schema/map section
Closes #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/349)
> add(doc): weekly doc update May 14th 2018

- src/locales/translations.csv
- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
closes #309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/351)
> fix(ref-to-legend): add refernce to layers panel

- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
Closes #353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/357)
> fix(form): Show name inside layer id for structured legend

- package-lock.json
- package.json
- src/app/core/constant.service.js
- src/app/geo/projection.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/version/version.directive.js
- src/app/ui/header/header.directive.js
- src/content/samples/config/config-extent-3857.json
- src/content/samples/config/config-extent-3978.json
- src/content/samples/extensions/extent.js
- src/content/samples/frame-extent.tpl
- src/locales/help/info-extentlods-en-CA.md
- src/locales/help/info-extentlods-fr-CA.md
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #288
Chrome with a new extent set not 3978, 3857 or 102100
Updated help section for extentset and lod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)
> fix(extent): Specify extent for every extentset to avoid bad projection

- src/locales/help/en-CA.md
- src/locales/help/fr-CA.md
closes #338
- [] Help files and documentation have been updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/358)
> feat(add accessibility) : add accessibility section to help file

- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/styles/modules/_forms.scss
Closes #360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/363)
> fix(form): init run twice

- src/app/core/core.run.js
- src/app/ui/forms/map/map.directive.js
closes #359
- [x ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/367)
> feat(expcolbasemaps): add expand collapse basemaps

- src/app/bootstrap.js
Closes #366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/368)
> feat(core): Disable/ warn browser preview button push

- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Add information about date format and filtering with dates
Closes #348
Schema description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/370)
> add(doc): update date filtering info

- wiki/schema-map.en-CA.md
add table node to schema doc in wiki
Closes #371
Wiki update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372)
> add(doc): weekly doc update June 4th-8th

- src/app/ui/forms/form.service.js
Add validation on load, template change and user file load.
Closes #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/383)
> add(form): add validation on load

- src/content/samples/config/canada-world-en.json
- src/content/samples/config/canada-world-fr.json
- src/content/samples/config/config-extent-3857.json
- src/content/samples/config/config-extent-3978.json
Closes #369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/386)
> fix(config): set proxy to https

- src/app/ui/forms/map/map.directive.js
- src/app/ui/summary/summary.directive.js
- src/schemas/schemaForm/map.en-CA.json
Closes #395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/396)
> fix(summary: bad validation for required item un dev version

- wiki/update-version.en-CA.md
Add guide to update Author version on wiki
Closes #397
wiki
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/399)
> add(doc): Author version update guide on wiki

- src/schemas/schema2.5.json
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/432)
> fix(schemaDoc): Add more description to wms id section

- src/app/core/common.service.js
- src/app/ui/forms/form.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/header/header.directive.js
- src/locales/translations.csv
closes #379
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/402)
> fix(help): add translation to error messages generated by angular schema forms

- src/content/samples/config/canada-world-en.json
- src/content/samples/config/canada-world-fr.json
- src/content/samples/config/config-extent-3857.json
- src/content/samples/config/config-extent-3978.json
- src/content/samples/config/config-sample.json
closes  #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/453)
> fix(template): add NRCan copyright to footnote

- src/app/core/constant.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/forms/version/version.directive.js
- src/app/ui/summary/summary.directive.js
- src/content/samples/config/canada-world-en.json
- src/content/samples/config/canada-world-fr.json
- src/content/samples/config/config-extent-3978.json
- src/content/samples/config/config-sample.json
- src/content/samples/frame-extent.tpl
- src/content/samples/frame-preview.tpl
- src/locales/translations.csv
- src/schemas/schema3.0.json
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/services.en-CA.json
- src/schemas/schemaForm/services.fr-CA.json
- src/schemas/schemaForm/version.en-CA.json
- src/schemas/schemaForm/version.fr-CA.json
- wiki/schema-map.en-CA.md
- wiki/update-version.en-CA.md
closes #439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/448)
> fix(schemaV3):added RAMP 3 support

- package-lock.json
- src/app/ui/forms/map/map.directive.js
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
CLoses #449
Test with layer provided inside samples config file no 85.
Try to make it work from deploy page with copy of those file on geoappext but doesn't work. We will have to do it manually
* https://geoappext.nrcan.gc.ca/fgpv/map/test/happy.json
* https://geoappext.nrcan.gc.ca/fgpv/map/test/Géochronologie.csv
* https://geoappext.nrcan.gc.ca/fgpv/map/test/ne_10m_ports.zip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/457)
> feat(map): Add a new layer type file

- src/content/samples/config/config-extent-3857.json
- src/content/samples/config/config-extent-3978.json
- src/content/samples/frame-extent.tpl
Closes #459
Revert to version 2.5.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/460)
> fix(extent): fix set extent doesn't work. Revert to viewer version 2.5.0

- package-lock.json
- src/app/core/constant.service.js
- src/app/ui/forms/map/map.directive.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/forms/version/version.directive.js
- src/app/ui/header/help.service.js
- src/app/ui/summary/summary.directive.js
- src/locales/help/info-legend-en-CA.md
- src/locales/help/info-legend-fr-CA.md
- src/locales/translations.csv
- src/schemas/schema3.1.json
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
- src/schemas/schemaForm/services.en-CA.json
- src/schemas/schemaForm/services.fr-CA.json
- src/schemas/schemaForm/version.en-CA.json
- src/schemas/schemaForm/version.fr-CA.json
- wiki/schema-map.en-CA.md
- wiki/schema-services.en-CA.md
Closes #465
Update to version 3.1 and add support for WFS layer. Update md file on wiki, Still need work to do on map layers section. We will see if it is needed. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/470)
> fix(schema): Update to work with the viewer version 3.1

- src/app/core/constant.service.js
- src/app/core/modelManager.service.js
- src/app/core/stateManager.service.js
- src/app/layout/shell.directive.js
- src/app/ui/forms/plugins/plugins.directive.js
- src/app/ui/forms/services/services.directive.js
- src/app/ui/summary/summary.directive.js
- src/app/ui/ui-loader.js
- src/content/samples/frame-preview.tpl
- src/locales/translations.csv
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Add plugin section with the range slider plugin in it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/471)
> feat(plugins): Add plugins configuration support (range slider)

- src/app/core/constant.service.js
- src/content/samples/config/all-layertype-sample.json
- src/schemas/schema3.1.json
- src/schemas/schema3.2.json
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
- src/schemas/schemaForm/version.en-CA.json
- src/schemas/schemaForm/version.fr-CA.json
Closes #476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/478)
> fix(schema): upgrade to viewer version 3.2

- src/app/core/common.service.js
Closes #502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/505)
> fix(preview): Not able to preview esriTile and esriImage layer

- src/app/ui/header/header.html
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
Closes #503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/510)
> fix(language): Special characters and language switcher

- package-lock.json
- package.json
- src/app/core/constant.service.js
- src/app/ui/forms/plugins/plugins.directive.js
- src/locales/translations.csv
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Closes #513
Closes #513
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/514)
> feat(plugin): Add swiper plugin

- src/app/ui/forms/ui/ui.directive.js
- src/locales/translations.csv
- src/schemas/schemaForm/ui.en-CA.json
- src/schemas/schemaForm/ui.fr-CA.json
Closes #518
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/520)
> fix(ui): Show order of navigation toolbar button

- src/app/core/constant.service.js
- src/app/ui/forms/plugins/plugins.directive.js
- src/locales/translations.csv
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Closes #519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/521)
> feat(plugin): Add draw toolbar plugin

- src/app/geo/layer.service.js
- src/app/ui/forms/map/map.directive.js
- src/content/styles/modules/_forms.scss
- src/locales/translations.csv
Closes #522
Make it as columns array are empty by default and add a buttons to removes all columns at the same time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/523)
> feat(layer): Default columns are empty and add a remove all columns

- package-lock.json
- package.json
- src/app/ui/forms/plugins/plugins.directive.js
- src/locales/translations.csv
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Closes #525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/529)
> fix(plugin): update draw with new parameters

- src/app/core/modelManager.service.js
- src/app/ui/forms/plugins/plugins.directive.js
- src/content/samples/frame-preview.tpl
- src/locales/translations.csv
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/map.fr-CA.json
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Closes #527
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/532)
> feat(plugin): Add thematic slider plugin

- src/app/core/constant.service.js
- src/app/core/modelManager.service.js
- src/app/core/stateManager.service.js
- src/app/ui/forms/plugins/plugins.directive.js
- src/content/samples/config/all-layertype-sample.json
- src/content/samples/config/all-plugins-sample.json
- src/content/samples/frame-preview.tpl
- src/locales/translations.csv
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Replace dev.gcgeo server by contributed-plugin repo deploy page for plugins code
Closes #533, #534, #535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/538)
> fix(plugins): update plugins with latest modifications

- src/locales/help/info-plugins-en-CA.md
- src/locales/help/info-plugins-fr-CA.md
closes(507)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/555)
> fix(helplinkplugins): open link in new tab

- package-lock.json
- package.json
- src/app/ui/forms/plugins/plugins.directive.js
- src/content/samples/config/canada-world-en.json
- src/content/samples/config/canada-world-fr.json
- src/content/samples/frame-extent.tpl
- src/content/samples/frame-preview.tpl
- src/content/styles/main.scss
- src/content/styles/modules/_forms.scss
- src/content/styles/vendor/_all.scss
- src/content/styles/vendor/_datepicker.scss
- src/schemas/schemaForm/map.en-CA.json
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
Closes #567
https://jolevesq.github.io/fgpa-apgf/samples/fgpv-author.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568)
> fix(slider): fix CSS, null array and converter years

- package.json
- src/app/ui/forms/plugins/plugins.directive.js
- src/app/ui/summary/summary.directive.js
- src/schemas/schemaForm/plugins.en-CA.json
- src/schemas/schemaForm/plugins.fr-CA.json
- webpack.prod.js
Closes #569)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/570)
> fix(plugins): Range slider missing info
